name: Generate Plugin Archive
on:
  push:
    tags:
      - "*"
jobs:
  create-archive:
    name: "Use Composer to Create Archive"
    runs-on: ubuntu-latest
    steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2.3.2
        - name: Install PHP
          uses: "shivammathur/setup-php@v2"
          with:
            php-version: "7.4"
        - name: Install Composer dependencies
          uses: "ramsey/composer-install@v2"
          with:
            composer-options: "--no-dev --optimize-autoloader --ignore-platform-reqs"
        - name: Run Build Script
          run: |
            chmod +x ./.github/install-fonts.sh
            ./.github/install-fonts.sh
          shell: bash
        - name: Insert Version Number
          run: |
            GITHUB_VERSION="${{github.ref_name}}"
            GITHUB_VERSION="${GITHUB_VERSION:1}"
            sed -i "s/GITHUB_VERSION/$GITHUB_VERSION/" babytuch-plugin.php
        - name: Build archive
          run: composer archive --format=zip --file babytuch-plugin
        - name: Upload Release
          uses: ncipollo/release-action@v1
          with:
            artifacts: "babytuch-plugin.zip"
            token: ${{ secrets.RELEASE_TOKEN }}